# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - test
      - main
pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  # retain git credentials after cloning, so we can push.
  # the pipeline runs as the user "Project Collection Build Service (devdiv)"
  persistCredentials: true
  
- script: |
    git checkout main
    git pull
    git merge origin/test -m "Merge test branch -> main"
    git push origin main --force
  displayName: 'Merge test -> main'


